CREATE DATABASE BDTEST
USE BDTEST
ALTER TABLE LOGIN
CREATE TABLE P_SEGURIDAD
(
USUARIO VARCHAR (25),
PASWORD VARCHAR (30)
 );
 
 select * from P_SEGURIDAD;
INSERT INTO P_SEGURIDAD (USUARIO, PASWORD) VALUES ('ladislao','ladislao123');
INSERT INTO P_SEGURIDAD (USUARIO, PASWORD) VALUES ('Carlos','carlos123')

INSERT INTO P_SEGURIDAD (USUARIO, PASWORD) VALUES('ADMISTRADOR','ADMIN123')