<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TODOIST</title>
    <img src="logoTODOIST.png" width="400" height="100"alt="AGENDA"/>
</head>
<body>
    <h1><center>BIENVENIDO A TODOIST</H1></center>
    <h4><center>¿Cómo planeas usar Todoist?</h4></center>
    <!--tr*6>td*3-->
    <tr>
        <td>
        </div> 
      <div <div style="text-align: center">
      <!--<div class="form-group">--> 
      
       <!--<button type="submit" class="btn btn-primary btn-block">-->

        <a href="pantalla_principal.HTML">
            <!--<button>Youtube</button>-->   
            <button onclick="button"> <img src="EDUCACION.png" height ="300" width="250" /></button>
            
        </a> 
       <!-- <button type="button"> <img src="EDUCACION.png" height ="300" width="250" /></button>-->
   
       
       <a href="para_trabajo.html">
       <button type="button"> <img src="TRABAJO.png" height ="300" width="250" ></button>
          <!-- btn-block : Botón que se expande en ancho según su contenedor</button> -->   
          <!--https://www.youtube.com/watch?v=4qUphI-AUKY--> 
</a>
             
      </div>

        </td>
    </tr>
     
   </body>
</html>