<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>login</title>
</head>
<body>
<form action="VALIDAR.PHP" method="post">
<h1>SISTEMA DE LOGIN</H1>
<P>USUARIO <input type="text"placeholder ="ingrese su nombre" name ="usuario"></p>
<P>PASSWORD <input type="password"placeholder ="ingrese contraseña" name ="contraseña"></p>
<input type="submit" value ="igresar">
</form> 
</body>
</html>